version: "3"

services:
  kafka_producer:
    container_name: producer
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: ${TWEET_TOPIC}
      BATCH_SIZE: ${TWEET_BATCH_SIZE}

networks:
  default:
    external:
      name: kafka-network
